// PNGResources.h

#pragma once

#include "Definitions.h"

#ifndef RPNG
#define RPNG extern RES_PNG
#endif

// Common

RPNG	RP_HEADER;
RPNG	RP_HEADER_LINE;
RPNG	RP_HEADER_DESC;
RPNG	RP_MESSAGE;

RPNG	RP_INPUT_W_DESC;
RPNG	RP_INPUT_WO_DESC;

RPNG	RP_YES_BTN;
RPNG	RP_NO_BTN;
RPNG	RP_YES_BTN_PRESS;
RPNG	RP_NO_BTN_PRESS;
RPNG	RP_YES_BTN_PAD;
RPNG	RP_NO_BTN_PAD;
RPNG	RP_YES_BTN_PAD_PRESS;
RPNG	RP_NO_BTN_PAD_PRESS;

// Annunciator

RPNG	RP_ANNUNCIATOR;
RPNG	RP_ANN_CONN[MAX_CONN_STATUS];
RPNG	RP_ANN_COUNT;
RPNG	RP_ANN_BATT[MAX_BATT_STATUS];
RPNG	RP_ANN_TIME;

// Menu

RPNG	RP_MENU_BOTTOM_LINE;

RPNG	RP_MENU_UNSELECTED[MENU_ITEMS_PER_PAGE];
RPNG	RP_MENU_SELECTED[MENU_ITEMS_PER_PAGE];
RPNG	RP_MENU_CHECKED[MENU_ITEMS_PER_PAGE];

RPNG	RP_MENU_UP_UNSELECTED;
RPNG	RP_MENU_UP_SELECTED;
RPNG	RP_MENU_DN_UNSELECTED;
RPNG	RP_MENU_DN_SELECTED;

// View

RPNG	RP_SWIPE;
RPNG	RP_WAIT;
RPNG	RP_BOTTOM;

RPNG	RP_PASSWORD_BOX;
RPNG	RP_PASSWORD_ASTERISK[LENGTH_PASSWORD];

RPNG	RP_PIN_BOX;
RPNG	RP_PIN_ASTERISK[LENGTH_PIN];

RPNG	RP_RESULT;
RPNG	RP_RESULT_TEXT;
RPNG	RP_SUCCESSFUL;
RPNG	RP_UNSUCCESSFUL;

RPNG	RP_PRINT;
RPNG	RP_PRINT_MESSAGE;

RPNG	RP_TRACE_NO_BOX;
RPNG	RP_TRACE_NO_NUMBER[LENGTH_TRACENO];

RPNG	RP_CITY_CODE_BOX;
RPNG	RP_CITY_CODE_NUMBER[LENGTH_CITY_CODE];

RPNG	RP_PHONE_BOX;
RPNG	RP_PHONE_NUMBER[LENGTH_PHONE_BOX];

RPNG	RP_DATE_BOX;
RPNG	RP_DATE_NUMBER[LENGTH_DATE];

RPNG	RP_TIME_BOX;
RPNG	RP_TIME_NUMBER[LENGTH_TIME];

RPNG	RP_BRIGHTNESS_BOX;
RPNG	RP_BRIGHTNESS_FILL[MAX_BRIGHTNESS];

RPNG	RP_SETTINGS_BOX;
RPNG	RP_SETTINGS_NUMBER[LENGTH_SETTINGS_BOX];

RPNG	RP_WEEKDAYS_BOX;
RPNG	RP_WEEKDAYS_FILL[MAX_WEEKDAYS];

RPNG	RP_IPADDRESS_BOX;
RPNG	RP_IPADDRESS_NUMBER[LENGTH_IPADDRESS];
RPNG	RP_PORT_BOX;
RPNG	RP_PORT_NUMBER[LENGTH_PORT];

// Device Specified

#if defined(MODEL_CT360)
RPNG	RP_INTRO_TOP;
#elif defined(MODEL_MT360)
RPNG	RP_INTRO_TOP;
#elif defined(MODEL_MT760)
RPNG	RP_INTRO_DATE;
RPNG	RP_INTRO_TIME;
#endif

#if GPRS_AVAILABLE
RPNG	RP_ANN_GPRS[MAX_GPRS_STATUS];
RPNG	RP_ANN_OPER;
#endif

#if SOFTWARE_KEYPAD
RPNG	RP_KEYPAD_BACK;
RPNG	RP_KEYPAD[MAX_KEYPAD];

RPNG	RP_FNKEY[MAX_FNKEY];
RPNG	RP_FNKEY_PRESS[MAX_FNKEY];
#endif
