// StringRes.h

#pragma once

// String IDs

#define IDS_NUM0								0x00
#define IDS_NUM1								0x01
#define IDS_NUM2								0x02
#define IDS_NUM3								0x03
#define IDS_NUM4								0x04
#define IDS_NUM5								0x05
#define IDS_NUM6								0x06
#define IDS_NUM7								0x07
#define IDS_NUM8								0x08
#define IDS_NUM9								0x09

#define IDS_F1KEY								0x0C
#define IDS_F2KEY								0x0D
#define IDS_F3KEY								0x0E
#define IDS_F4KEY								0x0F

#define	IDS_SUNDAY								0x10
#define IDS_MONDAY								0x11
#define IDS_TUESDAY								0x12
#define IDS_WEDNESDAY							0x13
#define IDS_THURSDAY							0x14
#define IDS_FRIDAY								0x15
#define IDS_SATURDAY							0x16

#define IDS_SWIPE_CARD							0x20
#define IDS_DIALUP								0x21
#define IDS_ENTER_PASSWORD						0x22
#define IDS_ENTER_PIN							0x23
#define IDS_ENTER_AMOUNT						0x24
#define IDS_CONFIRM_CANCEL						0x25
#define IDS_ENTER_BILL_ID						0x26
#define IDS_ENTER_PAYMENT_ID					0x27
#define IDS_CHARGE_COUNT						0x28
#define IDS_SELECT_PROVIDER						0x29
#define IDS_SELECT_CATEGORY						0x2A
#define IDS_PRINTING							0x2B
#define IDS_PRINT_RECEIPT						0x2C
#define IDS_PRINT_RETRY							0x2D
#define IDS_TRACE_NUMBER						0x2E
#define IDS_START_DATE							0x2F
#define IDS_END_DATE							0x30
#define IDS_ENTER_NEW_PASSWORD					0x31
#define IDS_VERIFY_PASSWORD						0x32
#define IDS_INFORMATION							0x3E
#define IDS_ERROR								0x3F

#define IDS_SALE								0x40
#define IDS_BALANCE								0x41
#define	IDS_BILL_PAYMENT						0x42
#define IDS_CHARGE								0x43
#define IDS_SELL_CHARGE							0x44
#define IDS_REPRINT								0x45
#define IDS_REPORTS								0x46
#define IDS_GOODS_BASKET						0x47
#define IDS_FOOD_SECURITY						0x48
#define IDS_CHANGE_PASSWORD						0x49
#define IDS_LOGON								0x4A
#define IDS_SERVICE_REQUEST						0x4B
#define IDS_CHANGE_CITY_CODE					0x4C
#define	IDS_PHONEBOOK							0x4D
#define IDS_SET_DATE							0x4E
#define IDS_SET_TIME							0x4F
#define IDS_BRIGHTNESS							0x50
#define IDS_LANGUAGE							0x51
#define IDS_SEND_PARAMETER						0x52
#define IDS_KEY_INJECTION						0x53
#define IDS_POS_SETTINGS						0x54
#define IDS_TMS_SETTINGS						0x55
#define IDS_DOWNLOAD_APPLICATION				0x56
#define IDS_MANUAL_UPDATE                       0x57
#define IDS_PRINT_TEST							0x58
#define IDS_SETTINGS_RESET_F2_PASSWORD			0x59
#define IDS_VERSION								0x5A
#define IDS_SELECTED_TRANSACTION				0x5B
#define IDS_TRANSACTION_DETAILS					0x5C
#define IDS_PAPER_REQUEST						0x5D
#define IDS_LIQUIDATE_REQUEST					0x5E
#define IDS_DEVICE_FAILURE						0x5F
#define IDS_SETTINGS_NII						0x60
#define IDS_SETTINGS_CONNECTION_TIMEOUT			0x61
#define IDS_SETTINGS_CONNECTED_TIMEOUT			0x62
#define IDS_SETTINGS_PIN_TIMEOUT				0x63
#define IDS_SETTINGS_ADVICE_TIMEOUT				0x64
#define IDS_SETTINGS_REVERSAL_TIMEOUT			0x65
#define IDS_SETTINGS_SCREEN_TIMEOUT				0x66
#define IDS_SETTINGS_CONNECTION_TYPE			0x67
#define IDS_SETTINGS_SERVER_SETTINGS			0x68
#define IDS_TMS_SETTINGS_STARTTIME				0x69
#define IDS_TMS_SETTINGS_ENDTIME				0x6A
#define IDS_TMS_SETTINGS_INTERVAL				0x6B
#define IDS_TMS_SETTINGS_COUNT					0x6C
#define IDS_TMS_SETTINGS_WEEKDAYS				0x6D

#define IDS_CARD_HOLDER_ONLY					0x80
#define IDS_PLEASE_WAIT							0x81
#define IDS_AMOUNT								0x82
#define IDS_BILL_ID								0x83
#define IDS_PAYMENT_ID							0x84
#define IDS_CHARGE_DESCRIPTION					0x85
#define IDS_PROVIDER							0x86
#define	IDS_CATEGORY							0x87
#define IDS_CHARGECOUNT							0x88
#define IDS_RIALS								0x89
#define IDS_PRESS_ANY_KEY						0x8A
#define IDS_PRESS_ENTER							0x8B

#define IDS_PROCESSING							0x90
#define IDS_DIALING								0x91
#define IDS_CONNECTING							0x92
#define IDS_CONNECTED							0x93
#define IDS_SENDING								0x94
#define IDS_RECEIVING							0x95
#define IDS_REVERSAL_MODE						0x96
#define IDS_CHECKING_UPDATES					0x97
#define IDS_LOW_BATTERY							0x98

#define IDS_PRINT_PURCHASE						0xA0
#define IDS_PRINT_BALANCE						0xA1
#define IDS_PRINT_BILL_PAYMENT					0xA2
#define IDS_PRINT_CHARGE_BUY					0xA3
#define IDS_PRINT_SELL_CHARGE					0xA4
#define IDS_PRINT_TRANSACTION_DETAILS			0xA5
#define IDS_PRINT_SERVICE_REQUEST				0xA6
#define IDS_PRINT_UNSUCCESSFUL					0xA7
#define IDS_PRINT_POS_INFORMATION				0xA8
#define IDS_CUSTOMER_RECEIPT					0xA9
#define IDS_ACCEPTOR_RECEIPT					0xAA
#define	IDS_TERMINAL_ID							0xAB
#define IDS_ACCEPTOR_ID							0xAC
#define IDS_CARD_ID								0xAD
#define IDS_BANK_NAME							0xAE
#define IDS_TRACE_NO							0xAF
#define IDS_DATE_TIME							0xB0
#define IDS_REFERENCE_NO						0xB1
#define IDS_RESPONSE_CODE						0xB2
#define IDS_AMOUNT_RIALS						0xB3
#define IDS_BALANCE_RIALS						0xB4
#define IDS_CUSTOMER_SOS						0xB5
#define IDS_RECEIPT_VERSION						0xB6
#define IDS_SERIAL								0xB7
#define IDS_CODE								0xB8
#define IDS_TIMEOUT_MESSAGE_1					0xB9
#define IDS_TIMEOUT_MESSAGE_2					0xBA
#define IDS_TIMEOUT_MESSAGE_3					0xBB
#define IDS_TIMEOUT_MESSAGE_4					0xBC
#define IDS_TIMEOUT_MESSAGE_5					0xBD
#define IDS_TIMEOUT_MESSAGE_6					0xBE
#define IDS_TIMEOUT_MESSAGE_7					0xBF
#define IDS_DETAILS_TYPE						0xC0
#define IDS_DETAILS_CARDNO						0xC1
#define IDS_DETAILS_AMOUNT						0xC2
#define IDS_DETAILS_TIME						0xC3
#define IDS_DETAILS_TRACENO						0xC4
#define IDS_DETAILS_NO							0xC5
#define IDS_COUNT_SALE							0xC6
#define IDS_COUNT_CHARGE						0xC7
#define IDS_COUNT_BILL							0xC8
#define IDS_TOTAL								0xC9
#define IDS_DESC_SALE							0xCA
#define IDS_DESC_CHARGE							0xCB
#define IDS_DESC_BILL_PAYMENT					0xCC

#define IDS_SUCCESSFUL							0xD0
#define IDS_UNSUCCESSFUL						0xD1
#define IDS_ERROR_INTERNAL_ERROR				0xD2
#define IDS_ERROR_NO_CARRIER					0xD3
#define IDS_ERROR_LINE_BUSY						0xD4
#define IDS_ERROR_NO_DIALTONE					0xD5
#define IDS_ERROR_TIMEOUT						0xD6
#define IDS_ERROR_GPRS_NOT_CONNECTED			0xD7
#define IDS_ERROR_HOST_NOT_RESOLVED				0xD8
#define	IDS_ERROR_DIALUP_FAILED					0xD9
#define IDS_ERROR_CONNECT_FAILED				0xDA
#define IDS_ERROR_SEND_FAILED					0xDB
#define IDS_ERROR_NO_RESPONSE					0xDC
#define IDS_ERROR_GPRS_NOT_READY				0xDD
#define IDS_ERROR_INVALID_PASSWORD				0xDE
#define IDS_ERROR_INVALID_PASSWORD_OVERFLOW		0xDF
#define IDS_ERROR_KEY_CARD_ERROR				0xE0
#define	IDS_ERROR_NO_RECORD_FOUND				0xE1
#define IDS_ERROR_LOGON_REQUIRED				0xE2
#define IDS_ERROR_INVALID_BILLID				0xE3
#define IDS_ERROR_INVALID_PAYMENTID				0xE4
#define IDS_ERROR_INTRO_NO_PAPER				0xE5
#define IDS_ERROR_PRINT_GENERIC					0xE6
#define IDS_ERROR_PRINT_NO_PAPER				0xE7
#define IDS_ERROR_PRINT_OVERHEAT				0xE8
#define IDS_ERROR_PRINT_LOWVOLTAGE				0xE9
#define IDS_ERROR_PRINT_HIGHVOLTAGE				0xEA
#define IDS_ERROR_INVALID_PIN_BLOCK				0xEB
#define IDS_ERROR_UNKNOWN_BANKID                0xEC
#define IDS_ERROR_NOT_IMPLEMENTED				0xFF

#define IDS_NOSTRING							0xFFFF

extern CString g_strEnglish[];
extern CString g_strFarsi[];
